import React from "react";

interface OgImageTemplateProps {
  title: string;
  description?: string;
  imageUrl?: string; // URL for the main image (game cover, player avatar)
  type: "game" | "player" | "default";
}

// Basic template component for Satori
// Uses inline styles with flexbox properties compatible with Satori/Yoga layout
export function OgImageTemplate({
  title,
  description,
  imageUrl,
  type,
}: OgImageTemplateProps) {
  const imageSize = type === "player" ? 200 : 400; // Smaller image for player
  const imageYPos = type === "player" ? 100 : 50;

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        width: "1200px",
        height: "630px",
        padding: "50px",
        backgroundColor: "#161A17", // Dark background
        color: "#FFFFFF", // White text
        fontFamily: "Inter", // Ensure you load this font in Satori
        fontSize: "32px",
      }}
    >
      <div style={{ display: "flex", alignItems: "center" }}>
        {imageUrl && (
          <img
            src={imageUrl}
            alt=""
            width={imageSize}
            height={imageSize}
            style={{
              borderRadius: type === "player" ? "50%" : "10px", // Circular for player, rounded for game
              marginRight: "40px",
              objectFit: "cover",
              marginTop: `${imageYPos}px`,
            }}
          />
        )}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            flexGrow: 1,
            marginTop: "50px",
          }}
        >
          <div
            style={{
              fontSize: "60px",
              fontWeight: 700,
              marginBottom: "20px",
              // Basic text wrapping simulation (Satori might handle this better)
              maxWidth: imageUrl
                ? `${1200 - 50 * 2 - imageSize - 40}px`
                : "100%",
              overflow: "hidden",
              textOverflow: "ellipsis",
              // Satori doesn't support whiteSpace: 'nowrap' directly well
              // but textOverflow might help
            }}
          >
            {title}
          </div>
          {description && (
            <div
              style={{
                fontSize: "36px",
                color: "#C0C0C0", // Lighter gray for description
                maxWidth: imageUrl
                  ? `${1200 - 50 * 2 - imageSize - 40}px`
                  : "100%",
                // Attempt multi-line text clamping (won't work perfectly in all SVG renderers)
                display: "-webkit-box",
                // WebkitLineClamp: 3, // Not standard SVG
                // WebkitBoxOrient: 'vertical', // Not standard SVG
                overflow: "hidden",
                textOverflow: "ellipsis",
                // Satori doesn't have great multi-line text support out of the box
              }}
            >
              {description}
            </div>
          )}
        </div>
      </div>
      {/* You could add a footer or logo here */}
      <div style={{ marginTop: "auto", fontSize: "24px", color: "#888888" }}>
        Generated by Arcade
      </div>
    </div>
  );
}

export default OgImageTemplate;
